services:
  - type: web
    name: ciberpaz-api
    env: dotnet
    plan: free
    region: oregon

    buildCommand: |
      dotnet restore
      dotnet publish -c Release -o out

    startCommand: |
      dotnet out/ciberpaz_api.dll

    autoDeploy: true

    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 10000
